use role role_data_engineer ;
use warehouse wh_commercial_analytics;
use database commercial_analytics;
use schema gold ; 

-- creation de la table sales_by_country
CREATE OR REPLACE TABLE SALES_BY_COUNTRY AS

SELECT
    COUNTRY,
    -- Chiffre d'affaires total par pays
    ROUND(
        SUM(TOTAL_AMOUNT),
        2
    ) AS TOTAL_SALES,

    -- Nombre de commandes distinctes par pays
    COUNT(DISTINCT SALE_ID) AS NUMBER_OF_ORDERS,

    -- Montant moyen d'une commande
    ROUND(
        SUM(TOTAL_AMOUNT) / COUNT(DISTINCT SALE_ID),
        2
    ) AS AVERAGE_ORDER_AMOUNT,

    -- Quantité totale de produits vendus
    SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD

FROM SILVER.SALES_CLEAN

GROUP BY COUNTRY

ORDER BY COUNTRY;

select * from sales_by_country
limit 10 ; 

-- creer la table sales by month 
CREATE OR REPLACE TABLE SALES_BY_MONTH AS

SELECT
    DATE_TRUNC('MONTH', SALE_DATE) AS SALE_MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT SALE_ID) AS NUMBER_OF_ORDERS,
    SUM(TOTAL_AMOUNT) / COUNT(DISTINCT SALE_ID) AS AVERAGE_ORDER_AMOUNT,
    SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM SILVER.SALES_CLEAN
GROUP BY DATE_TRUNC('MONTH', SALE_DATE)
ORDER BY SALE_MONTH;

-- creer la sales by country 
CREATE OR REPLACE TABLE GOLD.SALES_BY_COUNTRY AS

SELECT
    COUNTRY,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT SALE_ID) AS NUMBER_OF_ORDERS,
    SUM(TOTAL_AMOUNT) / COUNT(DISTINCT SALE_ID) AS AVERAGE_ORDER_AMOUNT,
    SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM SILVER.SALES_CLEAN
GROUP BY COUNTRY
ORDER BY COUNTRY;

-- creer la table top sales products 
CREATE OR REPLACE TABLE GOLD.TOP_PRODUCTS AS

SELECT
    PRODUCT_NAME,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT SALE_ID) AS NUMBER_OF_ORDERS,
    SUM(TOTAL_AMOUNT) / COUNT(DISTINCT SALE_ID) AS AVERAGE_ORDER_AMOUNT,
    SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM SILVER.SALES_CLEAN
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC;

-- creer la table top custumer 
CREATE OR REPLACE TABLE GOLD.TOP_CUSTOMERS AS

SELECT
    CUSTOMER_NAME,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT SALE_ID) AS NUMBER_OF_ORDERS,
    SUM(TOTAL_AMOUNT) / COUNT(DISTINCT SALE_ID) AS AVERAGE_ORDER_AMOUNT,
    SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM SILVER.SALES_CLEAN
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC;