-- tests 
use role role_data_engineer;
use warehouse wh_commercial_analytics;
use database commercial_analytics;
use schema commercial_analytics.silver;
USE SECONDARY ROLES NONE;

SELECT
    CUSTOMER_NAME,
    CUSTOMER_ADDRESS,
    CUSTOMER_PHONE
FROM SALES_CLEAN
LIMIT 10;

USE ROLE ROLE_MANAGER_FRANCE;
USE SECONDARY ROLES NONE;

SELECT
    CUSTOMER_NAME,
    CUSTOMER_ADDRESS,
    CUSTOMER_PHONE
FROM commercial_analytics.silver.SALES_CLEAN
LIMIT 10;

-- Donner les acces au role finance 
use role securityadmin; 

GRANT USAGE ON WAREHOUSE WH_COMMERCIAL_ANALYTICS
TO ROLE ROLE_FINANCE;

GRANT USAGE ON DATABASE COMMERCIAL_ANALYTICS
TO ROLE ROLE_FINANCE;

GRANT USAGE ON SCHEMA COMMERCIAL_ANALYTICS.SILVER
TO ROLE ROLE_FINANCE;

GRANT SELECT ON TABLE COMMERCIAL_ANALYTICS.SILVER.SALES_CLEAN
TO ROLE ROLE_FINANCE;

GRANT ROLE ROLE_FINANCE
TO USER didi242;

-- test sur role finance 
USE ROLE ROLE_FINANCE;
USE SECONDARY ROLES NONE;

USE WAREHOUSE WH_COMMERCIAL_ANALYTICS;
USE DATABASE COMMERCIAL_ANALYTICS;
USE SCHEMA SILVER;

SELECT
    CUSTOMER_NAME,
    CUSTOMER_ADDRESS,
    CUSTOMER_PHONE
FROM SALES_CLEAN
LIMIT 10;