use role role_data_engineer; 
use warehouse wh_commercial_analytics;
use database commercial_analytics; 
use schema commercial_analytics.gold ; 

show tables in schema commercial_analytics.gold ; 

-- tester sales by country 
SELECT *
FROM GOLD.SALES_BY_COUNTRY
ORDER BY COUNTRY;

SELECT COUNT(*) AS NUMBER_OF_COUNTRIES
FROM GOLD.SALES_BY_COUNTRY;

SELECT
    SUM(TOTAL_SALES) AS GOLD_TOTAL_SALES,
    SUM(NUMBER_OF_ORDERS) AS GOLD_NUMBER_OF_ORDERS,
    SUM(TOTAL_QUANTITY_SOLD) AS GOLD_TOTAL_QUANTITY
FROM GOLD.SALES_BY_COUNTRY;

-- tester sales by month
SELECT *
FROM GOLD.SALES_BY_MONTH
ORDER BY SALE_MONTH;

SELECT
    MIN(SALE_MONTH) AS FIRST_MONTH,
    MAX(SALE_MONTH) AS LAST_MONTH,
    COUNT(*) AS NUMBER_OF_MONTHS
FROM GOLD.SALES_BY_MONTH;

SELECT
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(TOTAL_QUANTITY_SOLD) AS TOTAL_QUANTITY
FROM GOLD.SALES_BY_MONTH;

-- top product 
-- ==========================================
-- 4. Tester TOP_PRODUCTS
-- ==========================================

SELECT *
FROM GOLD.TOP_PRODUCTS
ORDER BY TOTAL_SALES DESC
LIMIT 10;

SELECT
    COUNT(*) AS NUMBER_OF_PRODUCTS,
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(TOTAL_QUANTITY_SOLD) AS TOTAL_QUANTITY
FROM GOLD.TOP_PRODUCTS;


-- Vérifier que le classement est bien décroissant

SELECT
    PRODUCT_NAME,
    TOTAL_SALES
FROM GOLD.TOP_PRODUCTS
ORDER BY TOTAL_SALES DESC
LIMIT 5;

-- top custumers
SELECT *
FROM GOLD.TOP_CUSTOMERS
ORDER BY TOTAL_SALES DESC
LIMIT 10;

SELECT
    COUNT(*) AS NUMBER_OF_CUSTOMERS,
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(TOTAL_QUANTITY_SOLD) AS TOTAL_QUANTITY
FROM GOLD.TOP_CUSTOMERS;


-- Vérifier que le classement est bien décroissant

SELECT
    CUSTOMER_NAME,
    TOTAL_SALES
FROM GOLD.TOP_CUSTOMERS
ORDER BY TOTAL_SALES DESC
LIMIT 5;
